# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install webdriver-manager 
        ls -l /usr/bin/
        ls -l /usr/bin/google-chrome
        
    - name: Set up Chrome and Chromedriver
      run: |
        pip install webdrivermanager 

    - name: Set up Chrome 
      uses: browser-actions/setup-chrome@v1
      with:
          chrome-version: 121.0.6167 # This is the version of Google Chrome that was used

    - name: Run Robot Framework Tests
      run: |
          chrome --version
          webdrivermanager --version
          mkdir -p results  # Create a directory to store 
          pip list >> results/lista.txt
          ls -l >> results/directorio.txt

    - name: Test with robotframework
      run: |
        robot -v --outputdir results tests/loginTest.robot
