# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Install Google Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip
        wget -q "https://storage.googleapis.com/chrome-for-testing-public/131.0.6778.108/linux64/chrome-linux64.zip"
        unzip chrome-linux64.zip
        ls -l
        rm chrome-linux64.zip
      
    - name: Install Compatible ChromeDriver
      run: |
        sudo apt-get install -y wget unzip
        wget -q "https://storage.googleapis.com/chrome-for-testing-public/131.0.6778.108/linux64/chromedriver-linux64.zip"
        unzip chromedriver-linux64.zip
        ls -l
        rm chromedriver-linux64.zip
        sudo mv chrome-linux64 /usr/local/bin/
        sudo mv chromedriver-linux64 /usr/local/bin/

    - name: Test with robotframework
      run: |
        robot -d results/concise tests/loginTest.robot
